// let options = [
//   {
//     name: "East Asian",
//     answer_ids: [1],
//   },
//   {
//     name: "Japan",
//     answer_ids: [1,4]
//   }
// ];

// options.filter(option => {
//   option.answer_ids.includes(answer_id);
// });

// format raw data as above
Beer Garden (beergarden, [DE, CZ, AT, CH])
Beer Hall (beerhall, [DE, AT, CH])
Bistros (bistros, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW])
Brasseries (brasseries, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Breakfast & Brunch (breakfast_brunch, All)
Buffets (buffets, All)
Cafes (cafes, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Themed Cafes (themedcafes, [CL, PL, GB, IE, DE, AU, BE, AT, HK, DK, NL, NZ, SG, AR, MX, FI, US, FR, PH, SE, CH, JP, MY, TW, NO, CA])
Cafeteria (cafeteria, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IT, JP, MX, MY, NL, NO, PH, PL, PT, TR, TW, US])
Canteen (canteen, [IT, CZ, PL, FI, CH, JP, DE, AT, BE, DK, NL, NO])
Chicken Shop (chickenshop, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Comfort Food (comfortfood, [JP, CL, AR, MX, FI, US, CA])
Creperies (creperies, All)
Delis (delis, [AR, AT, AU, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, JP, MX, MY, NO, NZ, PH, PL, SG, TR, TW, US])
Diners (diners, [AR, AT, BE, BR, CA, CH, CL, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SG, TR, TW, US])
Dinner Theater (dinnertheater, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, MX, MY, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Fast Food (hotdogs, All)
Food Court (food_court, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, US])
Food Stands (foodstands, All)
Gastropubs (gastropubs, All)
Hong Kong Style Cafe (hkcafe, [US, HK, TW, CA])
Conveyor Belt Sushi (conveyorsushi, [IT, PL, US, SE, CH, JP, TW, DE, AT, BE, HK, NL, SG])
Milk Bars (milkbars, [AU, PL])
Night Food (nightfood, [TR, PL, DK, SE, NO])
Noodles (noodles, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Open Sandwiches (opensandwiches, [SE, DK, TR, NO])
Parent Cafes (eltern_cafes, [DE, AT, CH])
Pop-Up Restaurants (popuprestaurants, [GB, IE, DE, AU, BE, HK, DK, NL, NZ, SG, US, SE, FR, PH, MY, TW, NO, CA])
Poutineries (poutineries, [US, CA])
Pub Food (pubfood, [AU])
Soul Food (soulfood, [GB, PL, US, SE, IE, ES, NL, NO, CA])
Steakhouses (steak, All)
Supper Clubs (supperclubs, [US, ES, CA, GB])
Sushi Bars (sushi, All)
Tapas Bars (tapas, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Wok (wok, [AT, BE, CH, CL, CZ, DE, DK, ES, FI, FR, MX, MY, NL, NO, PH, PT, SE])
Asian Fusion (asianfusion, All)
Baguettes (baguettes, [IT, TR, CZ, MX, SE, PT, DE, NO])
Barbeque (bbq, [AR, AT, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Pancakes (pancakes, All)
Burgers (burgers, All)
Cheesesteaks (cheesesteaks, [AU, GB, PL, NL, US, IE, CA])
Chicken Wings (chicken_wings, [AR, AT, AU, BR, CA, CZ, DE, GB, HK, IE, MX, MY, NZ, PH, PL, SE, SG, TR, TW, US])
Curry Sausage (currysausage, [DE, AT, CH])
Dumplings (dumplings, [GB, PL, IE, CH, JP, DE, AU, BE, AT, NL, NZ, SG, CA])
Fish & Chips (fishnchips, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
Flatbread (flatbread, [DE, PL, AT, DK, CH])
Fondue (fondue, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Game Meat (gamemeat, [AT, AU, BE, CH, CZ, DE, DK, ES, FR, GB, IE, IT, NL, NO, NZ, PL, SE, SG, US])
Hot Dogs (hotdog, All)
Ramen (ramen, All)
Tempura (tempura, [JP, SG, TW])
Kebab (kebab, All)
Live/Raw Food (raw_food, All)
Meatballs (meatballs, [BE, FR, TR, NL])
Falafel (falafel, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
Tacos (tacos, [MX, US])
Pita (pita, [TR])
Pizza (pizza, All)
Polish (polish, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
Pierogis (pierogis, [PL])
Potatoes (potatoes, [DE, AU, AT, CH])
Rice (riceshop, [JP, TR])
Rotisserie Chicken (rotisserie_chicken, [IT, CL, AR, BR, PL, MX, FR, PT, AU, BE, ES, NZ, NL])
Salad (salad, All)
Sandwiches (sandwiches, All)
Schnitzel (schnitzel, [DE, PL, AT, CH])
Soup (soup, All)
Tapas/Small Plates (tapasmallplates, All)
Waffles (waffles, All)
Wraps (wraps, [TR, CZ, DK, US, SE, PT, NO])
Afghan (afghani, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
African (african, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
South African (southafrican, [IT, AU, BE, US, FR, CA])
American (New) (newamerican, [GB, DK, US, SE, IE, NO])
American (Traditional) (tradamerican, All)
Arabian (arabian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Argentine (argentine, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Armenian (armenian, [IT, TR, AR, CZ, GB, PL, US, FR, BE, ES])
Australian (australian, All)
Austrian (austrian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Bangladeshi (bangladeshi, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Belgian (belgian, All)
Flemish (flemish, [FR])
Black Sea (blacksea, [TR])
Brazilian (brazilian, All)
British (british, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Bulgarian (bulgarian, [AR, AT, AU, BE, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, PH, PL, PT, SE, TW, US])
Cajun/Creole (cajun, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TR, TW, US])
Cambodian (cambodian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Canadian (New) (newcanadian, [CA])
Caribbean (caribbean, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Dominican (dominican, [US])
Haitian (haitian, [US, CA])
Puerto Rican (puertorican, [US])
Chilean (chilean, [FR, FI, BR, CL])
Chinese (chinese, All)
Cuban (cuban, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
Czech (czech, [IT, CZ, GB, PL, FI, US, SE, FR, IE, DE, AU, BE, DK, NO, CA])
Danish (danish, [FR, SE, DK, NO])
Eastern European (eastern_european, [CZ, AU, DK, FR, NO])
Ethiopian (ethiopian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
Filipino (filipino, [AR, AT, AU, BE, BR, CA, CH, CL, DE, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
French (french, All)
Georgian (georgian, [CZ, PL, GB, FI, US, CH, AT, DE])
German (german, All)
Greek (greek, All)
Guamanian (guamanian, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, IT, MY, NL, NO, NZ, PH, PT, SE, SG, TW, US])
Hawaiian (hawaiian, [AR, AT, BE, BR, CA, CH, CL, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Honduran (honduran, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Hungarian (hungarian, All)
Iberian (iberian, [US, PT, CA])
Indian (indpak, All)
Indonesian (indonesian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Irish (irish, All)
Israeli (israeli, [DE, CZ, AT, CH])
Italian (italian, All)
Japanese (japanese, All)
Japanese Curry (japacurry, [JP, TW, HK, US, SG])
Western Style Japanese Food (westernjapanese, [JP, SG, TW])
Jewish (jewish, [IT, DE, PL])
Korean (korean, All)
Latin American (latin, All)
Colombian (colombian, [CL, AR, MX, FI, US, FR, BE, ES, CA])
Salvadoran (salvadoran, [US, CA])
Venezuelan (venezuelan, [CL, AR, ES, US, FR, PT, CA])
Malaysian (malaysian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Mediterranean (mediterranean, All)
Mexican (mexican, All)
Middle Eastern (mideastern, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Egyptian (egyptian, [IT, BE, US, FR, CA])
Lebanese (lebanese, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Modern Australian (modern_australian, [AU])
Modern European (modern_european, All)
Mongolian (mongolian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Moroccan (moroccan, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
New Mexican Cuisine (newmexican, [US])
New Zealand (newzealand, [NZ])
Nicaraguan (nicaraguan, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Oriental (oriental, [DE, AT, PL, FR, PT, CH])
Pakistani (pakistani, All)
Pan Asian (panasian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Parma (parma, [AU])
Persian/Iranian (persian, All)
Peruvian (peruvian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TW, US])
Polynesian (polynesian, [US])
Portuguese (portuguese, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Romanian (romanian, [CZ, PL, FR, CH, DE, AT, BE, ES])
Russian (russian, All)
Scandinavian (scandinavian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
Scottish (scottish, [DE, GB, AT, US, IE, CA, CH])
Seafood (seafood, All)
Singaporean (singaporean, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Slovakian (slovakian, [IT, CZ, GB, PL, US, FR, IE, AU, BE, CA])
Somali (somali, [IT, DE, PL, AT, US, CH])
Southern (southern, [TR, GB, PL, US, SE, IE, NL, NZ, CA])
Spanish (spanish, All)
Sri Lankan (srilankan, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
Swedish (swedish, [SE])
Swiss Food (swissfood, [CL, AR, CZ, DE, MX, ES, CH])
Syrian (syrian, All)
Taiwanese (taiwanese, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Tex-Mex (tex-mex, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
Thai (thai, All)
Traditional Norwegian (norwegian, [FR, NO])
Traditional Swedish (traditional_swedish, [SE, FI])
Turkish (turkish, All)
Ukrainian (ukrainian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
Uzbek (uzbek, [CZ, US])
Vietnamese (vietnamese, All)
Gluten-Free (gluten_free, All)
Halal (halal, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Kosher (kosher, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
Vegan (vegan, All)
Vegetarian (vegetarian, All)