Question.create!(query: "Which of these condiments would you never eat?")
Question.create!(query: "Would you eat something you don't like if you were very hungry?")
Question.create!(query: "Would you rather never be able to taste something sweet for the rest of your life, or never be able to taste something savory?")
Question.create!(query: "Pick an animal")
Question.create!(query: "If you had to choose, would you rather never eat fruit, or never eat vegetables?")
Question.create!(query: "Which cake is best cake?")
Question.create!(query: "You can only eat one flavor of ice cream for the rest of you life - which would it be?")
Question.create!(query: "Are carbs a priority?")
Question.create!(query: "What's for breakfast?")
Question.create!(query: "Pick a pie:")
Question.create!(query: "Favorite hot beverage?")
Question.create!(query: "It's midnight. You're running to the fridge. What are you grabbing?")
Question.create!(query: "Pick a sandwich:")
Question.create!(query: "Favorite cocktail?")
Question.create!(query: "Pick a soup:")
Question.create!(query: "Pick a pasta:")
Question.create!(query: "What's your starbucks order?")
Question.create!(query: "How do you commute?")
Question.create!(query: "What's your favorite season?")
Question.create!(query: "You're going out. What's your preferred venue?")
Question.create!(query: "You're stranded on a desert island and you have one meal you can eat for a year...what is it?")
Question.create!(query: "Pick your essential, must-have ingredient:")
Question.create!(query: "From Hard Rock Cafe to date night romance, what kind of atmosphere are you looking for?")
Question.create!(query: "What do you like on your bagel?")
Question.create!(query: "If you could only have one topping on your pizza, what would it be?")
Question.create!(query: "Which do you prefer for a vacation: beach or foreign city?")
Question.create!(query: "What's on your hot dog?")
Question.create!(query: "Any little ones joining the party?")
Question.create!(query: "How easily do you get lost without GPS?")
Question.create!(query: "What do you dip your fries in?")
Question.create!(query: "What do you put on your toast?")
Question.create!(query: "Deep frying anything... what oil do you use?")
Question.create!(query: "Best use of potatoes?")
Question.create!(query: "Pancakes or waffles?")
Question.create!(query: "Bacon?")
Question.create!(query: "How do you like your fries?")
Question.create!(query: "Favorite comedy?")
Question.create!(query: "Bacon?")
Question.create!(query: "Seafood, meat, or veg?")
Question.create!(query: "Dream city to live in?")
Question.create!(query: "What age do you wish you could permanently be?")
Question.create!(query: "Pick an outdoor ativity:")
Question.create!(query: "How much do you tip your server/delivery driver? (Don't worry, we won't tell...)")
Question.create!(query: "Biggest fear?")
Question.create!(query: "Pick a smell:")
Question.create!(query: "Which season of Chef's Table was your favorite?")
Question.create!(query: "Dumplings or sandwiches?")
Question.create!(query: "Pick a dystopian universe:")
