SearchFilter.create!(category: "Cuisine")
SearchFilter.create!(category: "Establishment type")
SearchFilter.create!(category: "Food type")
SearchFilter.create!(category: "Dietary restrictions")

QuestionFormat.create!(format: "Multiple Choice")
QuestionFormat.create!(format: "Scale")
QuestionFormat.create!(format: "True or False")

# ----- Tom's Questions -------------------------------------------------------------------------------->

Question.create!(query: "Leave the gun, take the.... ?", question_format_id: 1)
Question.create!(query: "Did you enjoy the Sopranos final eipsode?", question_format_id: 3)
Question.create!(query: "On a scale of 1 to Hangry, how are you feeling?", question_format_id: 2)
Question.create!(query: "Early bird or night owl?", question_format_id: 3)
Question.create!(query: "How many wheels do you normally travel on?", question_format_id: 1)
Question.create!(query: "When you go to a friend's house, do you bring...?", question_format_id: 1)
Question.create!(query: "Budget buffet or feeling fancy?", question_format_id: 2)
Question.create!(query: "How many people know your middle name?", question_format_id: 1)
Question.create!(query: "Pick a color:", question_format_id: 1)
Question.create!(query: "What do you typically do with leftovers?", question_format_id: 1)
Question.create!(query: "How clean is your bathroom right now?", question_format_id: 2)
Question.create!(query: "If you received a free ticket to anywhere, where would you go?", question_format_id: 1)
Question.create!(query: "What is the worst sensation, of the following:", question_format_id: 1)
Question.create!(query: "Cheese or chocolate?", question_format_id: 3)
Question.create!(query: "Would you rather never add salt to anything again or never add sugar to anything again?", question_format_id: 3)
Question.create!(query: "Would you rather never be able to use condiments again or have to add condiments to everything you eat?", question_format_id: 3)
Question.create!(query: "Would you rather have to eat everything hot or have to eat everything cold?", question_format_id: 3)
Question.create!(query: "Breakfast or dinner?", question_format_id: 3)
Question.create!(query: "What item do you get EVERY TIME you go to the grocery store?", question_format_id: 1)
Question.create!(query: "Would you rather add chili pepper to everything you eat or add lemon juice to everything you eat?", question_format_id: 3)
Question.create!(query: "Wine or beer?", question_format_id: 3)
Question.create!(query: "How do you take your coffee?", question_format_id: 1)
Question.create!(query: "Do you always add to much salt to your food or too much pepper to your food?", question_format_id: 3)
Question.create!(query: "Would rather eat only cheese or only meat the rest of your life?", question_format_id: 3)

# ----- Tehilla's Questions -------------------------------------------------------------------------------->
Question.create!(query: "Would you rather eat the same thing every day or never be able to eat the same thing twice?", question_format_id: 3)
Question.create!(query: "If it meant you could save pizza from extinction, would you eat a cricket?", question_format_id: 3)
Question.create!(query: "Willing to walk or was today leg day?", question_format_id: 2)
Question.create!(query: "If you were responsible for choosing whether the world would have bagels or donuts, which one would you choose?", question_format_id: 3)
Question.create!(query: "How spicy do you like your food?", question_format_id: 1)
Question.create!(query: "Favorite reality TV show?", question_format_id: 1)
Question.create!(query: "Would you rather eat potatoes with every meal or rice with every meal?", question_format_id: 3)
Question.create!(query: "Of the following, what is your favorite fast food restaurant?", question_format_id: 1)
Question.create!(query: "Do you have a sweet tooth?", question_format_id: 3)
Question.create!(query: "What outfit are you wearing right now?", question_format_id: 1)
Question.create!(query: "How adventurous are you feeling?", question_format_id: 1)
Question.create!(query: "Which mythological creature do you wish were real?")
Question.create!(query: "Do you have a sweet tooth?", question_format_id: 3)
Question.create!(query: "Which mythological creature do you wish were real?", question_format_id: 1)
Question.create!(query: "Do you grow your own herbs?", question_format_id: 3)
Question.create!(query: "What unusual food would you prefer?", question_format_id: 1)
Question.create!(query: "Favorite breakfast cereal:", question_format_id: 1)
Question.create!(query: "How high are you right now?", question_format_id: 2)
Question.create!(query: "Which type of movie would you rather see?", question_format_id: 1)
Question.create!(query: "Is bowling a sport?", question_format_id: 3)
Question.create!(query: "Pick a sport", question_format_id: 1)
Question.create!(query: "Pick an amusement park ride", question_format_id: 1)
Question.create!(query: "Which best describes your current mood?", question_format_id: 1)
Question.create!(query: "What's your favorite vegetable?", question_format_id: 1)
Question.create!(query: "Last minute reservation?", question_format_id: 3)
Question.create!(query: "How many slices of pizza can you eat in a single sitting?", question_format_id: 1)
# ----- Kayla's Questions -------------------------------------------------------------------------------->

Question.create!(query: "Which of these condiments would you never eat?", question_format_id: "1")
Question.create!(query: "Would you eat something you don't like if you were very hungry?", question_format_id: "3")
Question.create!(query: "Would you rather never be able to taste something sweet for the rest of your life, or never be able to taste something savory?", question_format_id: "3")
Question.create!(query: "Pick an animal", question_format_id: "1")
Question.create!(query: "If you had to choose, would you rather never eat fruit, or never eat vegetables?", question_format_id: "3")
Question.create!(query: "Which cake is best cake?", question_format_id: "1")
Question.create!(query: "You can only eat one flavor of ice cream for the rest of you life - which would it be?", question_format_id: "1")
Question.create!(query: "Are carbs a priority?", question_format_id: "3")
Question.create!(query: "What's for breakfast?", question_format_id: "1")
Question.create!(query: "Pick a pie:", question_format_id: "1")
Question.create!(query: "Favorite hot beverage?", question_format_id: "1")
Question.create!(query: "It's midnight. You're running to the fridge. What are you grabbing?", question_format_id: "1")
Question.create!(query: "Pick a sandwich:", question_format_id: "1")
Question.create!(query: "Favorite cocktail?", question_format_id: "1")
Question.create!(query: "Pick a soup:", question_format_id: "1")
Question.create!(query: "Pick a pasta:", question_format_id: "1")
Question.create!(query: "What's your starbucks order?", question_format_id: "1")
Question.create!(query: "How do you commute?", question_format_id: "1")
Question.create!(query: "What's your favorite season?", question_format_id: "1")
Question.create!(query: "You're going out. What's your preferred venue?", question_format_id: "1")
Question.create!(query: "You're stranded on a desert island and you have one meal you can eat for a year...what is it?", question_format_id: "1")
Question.create!(query: "Pick your essential, must-have ingredient:", question_format_id: "1")
Question.create!(query: "From Hard Rock Cafe to date night romance, what kind of atmosphere are you looking for?", question_format_id: "1")
Question.create!(query: "What do you like on your bagel?", question_format_id: "1")
Question.create!(query: "If you could only have one topping on your pizza, what would it be?", question_format_id: "1")

# ----- Adam's Questions -------------------------------------------------------------------------------->

Question.create!(query: "Which do you prefer for a vacation: beach or foreign city?", question_format_id: 3)
Question.create!(query: "What's on your hot dog?", question_format_id: 1)
Question.create!(query: "Any little ones joining the party?", question_format_id: 3)
Question.create!(query: "How easily do you get lost without GPS?", question_format_id: 2)
Question.create!(query: "What do you dip your fries in?", question_format_id: 1)
Question.create!(query: "What do you put on your toast?", question_format_id: 1)
Question.create!(query: "Deep frying anything... what oil do you use?", question_format_id: 1)
Question.create!(query: "Best use of potatoes?", question_format_id: 1)
Question.create!(query: "Pancakes or waffles?", question_format_id: 3)
Question.create!(query: "Bacon?", question_format_id: 3)
Question.create!(query: "How do you like your fries?", question_format_id: 1)
Question.create!(query: "Favorite comedy?", question_format_id: 1)
Question.create!(query: "Bacon?", question_format_id: 1)
Question.create!(query: "Seafood, meat, or veg?", question_format_id: 1)
Question.create!(query: "Dream city to live in?", question_format_id: 1)
Question.create!(query: "What age do you wish you could permanently be?", question_format_id: 1)
Question.create!(query: "Pick an outdoor ativity:", question_format_id: 1)
Question.create!(query: "How much do you tip your server/delivery driver? (Don't worry, we won't tell...)", question_format_id: 1)
Question.create!(query: "Biggest fear?", question_format_id: 1)
Question.create!(query: "Pick a smell:", question_format_id: 1)
Question.create!(query: "Which season of Chef's Table was your favorite?", question_format_id: 1)
Question.create!(query: "Dumplings or sandwiches?", question_format_id: 3)
Question.create!(query: "Pick a dystopian universe:", question_format_id: 1)
